---
Name: instagram-token-refresh
---
Silverstripe\SiteConfig\SiteConfig:
  extensions:
    - Dynamic\InstagramToken\ORM\SiteConfigExtension

SilverStripe\CMS\Model\SiteTree:
  extensions:
    - Dynamic\InstagramToken\ORM\SiteTreeExtension
